### ISSUE TITLE
LUA errors on non-"mr_" maps

### ISSUE THREAD

**Issue by Patrxgt** [figardo/MelonRacer#1]
Like in the title, when I launch Melon Racer gamemode on any other map than official MR maps game starts to generate lots of LUA errors.

**Comment by figardo** [comment]
- which specific maps cause the lua errors
- have you tried disabling all addons except melonracer before loading into these maps

**Comment by Patrxgt** [comment]
- I've tried multiple versions of gm_construct, gm_bigcity and gm_flatgrass
- Yes, MelonRacer is the only one, that gives me problems

BTW. I've also tried changing between 32 and 64 bit builds and game still generates LUA errors.

**Comment by figardo** [comment]
> * I've tried multiple versions of gm_construct, gm_bigcity and gm_flatgrass
> * Yes, MelonRacer is the only one, that gives me problems
> 
> BTW. I've also tried changing between 32 and 64 bit builds and game still generates LUA errors.

odd, i'm not getting any errors on those maps

do you get the errors by loading a specific track on each map or just as you load into the map?
if you do load a track, could you send the tracks you're trying to load

also, if you could send me the error itself that would be great (probably the first thing i should have asked, whoops)

**Comment by Patrxgt** [comment]
I'm not loading any tracks, I'm just checking Melon Racer gamemode and load into the map through menu.

Those are the errors, when I just load the Melon Racer mode on non mr_ maps:
![obraz](https://github.com/figardo/MelonRacer/assets/62941214/1bc761f7-ce3d-4f18-82f5-d2d611f8773a)

And those are the errors, when I first load to map in Sandbox mode, go back to the menu and then return to the same map in the Melon Racer mode:
![obraz](https://github.com/figardo/MelonRacer/assets/62941214/95b047ce-d7f7-4214-a4d4-df9232ed2580)

Also, the more I play, the more I get of those second errors. My record is 5000 errors lol

**Comment by figardo** [comment]
hopefully fixed with the next update
https://github.com/figardo/MelonRacer/commit/a637ca6398c74d7e612d8ed5077af1dacee694e6
